apiVersion: apps/v1
kind: Deployment
metadata:
  name: phraseanet-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phraseanet
      tier: rabbitmq
  template:
    metadata:
      labels:
        app: phraseanet
        tier: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
{{ toYaml .Values.rabbitmq.resources | indent 12 }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.default_user }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.default_pass }}
