sbas_id:
  name: sbas_id
  in: path
  description: ID of the databox
  required: true
  schema:
    $ref: common.yaml#/ID

base_id:
  name: base_id
  in: path
  description: ID of the base
  required: true
  schema:
    $ref: common.yaml#/ID

record_id:
  name: record_id
  in: path
  description: ID of the record
  required: true
  schema:
    $ref: common.yaml#/ID

query:
  name: query
  in: query
  description: 'Fulltext query (<empty> = search all)'
  required: false
  schema:
    type: string
    example: 'dogs OR cats'
    default: ''

search_type:
  name: search_type
  in: query
  required: false
  schema:
    type: integer
    enum: [0,1]
    default: 0
  description: >
    search for records or stories
      * `0` - search for records
      * `1` - search for stories

page:
  name: page
  in: query
  description: page number, from 1. Use along with "per_page"
  required: false
  schema:
    type: integer
    minimum: 1
    default: 1

per_page:
  name: per_page
  in: query
  description: number of results per page. Use along with "page"
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 10

offset:
  name: offset
  in: query
  description: offset in records count, from 0. Use along with "limit"
  required: false
  schema:
    type: integer
    minimum: 0
    # default: 0

limit:
  name: limit
  in: query
  description: number of results. Use along with "offset"
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 100
    # default:
